[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

[project]
name = "exogress"
#classifiers = [
#    "Programming Language :: Python",
#    "Programming Language :: Rust"
#]
requires-python = ">=3.6"
description = "Exogress Client for Python"
